import type { Metadata } from 'next';

import { LINESeedJP } from '@/libs/next-font';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className={LINESeedJP.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
