import { ColorSchemeScript } from '@mantine/core';
import '@mantine/core/styles.css';

import type { Metadata } from 'next';

import { CustomMantineProvider } from '@/libs/mantine/provider';
import { LINESeedJP } from '@/libs/next-font';

import { Noise } from './_components/Noise';
import styles from './global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    minimumScale: 1,
    initialScale: 1,
    width: 'device-width',
    userScalable: false,
  },
  icons: [
    {
      rel: 'apple-touch-icon',
      url: '/apple-touch-icon.png',
      sizes: '180x180',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: '/favicon-32x32.png',
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: '/favicon-16x16.png',
    },
  ],
  manifest: '/site.webmanifest',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja" className={styles.resetHeight}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${LINESeedJP.className} ${styles.resetHeight}`}>
        <CustomMantineProvider>
          <Noise />
          {children}
        </CustomMantineProvider>
      </body>
    </html>
  );
};

export default RootLayout;
